# Generated by Django 5.2.8 on 2025-11-30 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Nome do pedido', max_length=255, verbose_name='Nome')),
                ('value', models.DecimalField(decimal_places=2, help_text='Valor do pedido', max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(choices=[('paid', 'Pago'), ('pending', 'Pendente'), ('canceled', 'Cancelado')], help_text='Status do pedido', max_length=255, verbose_name='Status')),
                ('installments', models.IntegerField(default=1, help_text='Parcelas do pedido', verbose_name='Parcelas')),
                ('seller', models.ForeignKey(blank=True, help_text='Vendedor do pedido', null=True, on_delete=django.db.models.deletion.CASCADE, to='sellers.seller', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
