# Generated by Django 5.2.8 on 2025-12-01 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(help_text='Vendedor do pedido', on_delete=django.db.models.deletion.CASCADE, to='sellers.seller', verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='value',
            field=models.FloatField(default=0, help_text='Valor do pedido', verbose_name='Valor'),
        ),
    ]
