# Generated by Django 5.2.8 on 2025-12-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_seller_alter_order_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0, help_text='Total do pedido', verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='order',
            name='value_freight',
            field=models.FloatField(default=0, help_text='Valor do frete do pedido', verbose_name='Valor do Frete'),
        ),
    ]
