# Generated by Django 5.2.8 on 2025-12-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_total_order_value_freight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, help_text='Total do pedido', max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='Valor do pedido', max_digits=10, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='value_freight',
            field=models.DecimalField(decimal_places=2, help_text='Valor do frete', max_digits=10, verbose_name='Valor do frete'),
        ),
    ]
