# Generated by Django 5.2.8 on 2025-12-30 01:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='installments',
            field=models.IntegerField(default=1, help_text='Parcelas do pedido', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Parcelas'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('failed', 'Falhou'), ('canceled', 'Cancelado')], db_index=True, help_text='Status do pedido', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, help_text='Total do pedido', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='Valor do pedido', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='value_freight',
            field=models.DecimalField(decimal_places=2, help_text='Valor do frete', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor do frete'),
        ),
    ]
