# Generated by Django 5.2.8 on 2025-12-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_order_installments_alter_order_status_and_more"),
        ("sellers", "0003_seller_commission_rate_seller_user"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["created_at"], name="orders_created_77e2b9_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["seller", "created_at"], name="orders_seller__c2b5ff_idx"
            ),
        ),
    ]
