# Generated by Django 5.2.8 on 2025-12-30 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sellers", "0003_seller_commission_rate_seller_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "date",
                    models.DateField(
                        help_text="Data em que a venda foi realizada",
                        verbose_name="Data da Venda",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor total vendido no dia (ex: 8500.00)",
                        max_digits=12,
                        verbose_name="Valor Total",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Observações opcionais sobre a venda",
                        verbose_name="Observações",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_sales",
                        to="sellers.seller",
                        verbose_name="Vendedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venda Diária",
                "verbose_name_plural": "Vendas Diárias",
                "db_table": "daily_sales",
                "ordering": ["-date", "seller__name"],
                "indexes": [
                    models.Index(fields=["date"], name="daily_sales_date_34eaa5_idx"),
                    models.Index(
                        fields=["seller", "date"], name="daily_sales_seller__bf639c_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("seller", "date"), name="unique_seller_date"
                    )
                ],
            },
        ),
    ]
