# Generated by Django 5.2.8 on 2025-12-30 03:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailysale",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Valor total vendido no dia",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Valor",
            ),
        ),
        migrations.AlterField(
            model_name="dailysale",
            name="date",
            field=models.DateField(
                db_index=True, help_text="Data da venda", verbose_name="Data"
            ),
        ),
        migrations.AlterField(
            model_name="dailysale",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Observações sobre as vendas do dia (opcional)",
                null=True,
                verbose_name="Observações",
            ),
        ),
    ]
