# Generated by Django 5.2.8 on 2025-12-30 01:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(help_text='Telefone do vendedor (formato: +5511999999999)', max_length=20, validators=[django.core.validators.RegexValidator(message='Número de telefone inválido. Use formato internacional: +5511999999999', regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone'),
        ),
    ]
