# Generated by Django 5.2.8 on 2025-12-30 02:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0002_alter_seller_phone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Percentual de comissão sobre vendas (0-100)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="% Comissão",
            ),
        ),
        migrations.AddField(
            model_name="seller",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Usuário para login no painel do vendedor",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="seller_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
    ]
