# Generated by Django 5.2.8 on 2025-12-14 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_amount_alter_paymentlink_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='payments.paymentlink', verbose_name='Link de pagamento'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('pending', 'Pendente'), ('inactive', 'Inativo'), ('expired', 'Expirado'), ('paid', 'Pago'), ('canceled', 'Cancelado')], default='pending', max_length=50, verbose_name='Status'),
        ),
    ]
