# Generated by Django 5.2.8 on 2025-12-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_payment_link_alter_paymentlink_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlink',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('expired', 'Expirado'), ('used', 'Usado'), ('canceled', 'Cancelado')], default='active', max_length=50, verbose_name='Status'),
        ),
    ]
