# Generated by Django 5.2.8 on 2025-12-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_paymentlink_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('paid', 'Pago'), ('failed', 'Falhou'), ('canceled', 'Cancelado'), ('refunded', 'Reembolsado'), ('chargeback', 'Chargeback'), ('overpaid', 'Pago a mais'), ('underpaid', 'Pago a menos')], default='pending', max_length=50, verbose_name='Status'),
        ),
    ]
